import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideNavigation from "./pageComponents/sideNavigation";
import {NavigationMenuDemo} from "./pageComponents/desktopNavigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="">
          <div className="flex flex-row">
          <SideNavigation />
          <NavigationMenuDemo />
          </div>
          <div className="relative ml-15 mt-15 min-w-[95vw]">
           {children}
          </div>
        </div>
      </body>
    </html>
  );
}
